import { z } from 'zod';
import { JsonValue, ModelUsage, Usage, UserInput } from './common.ts';

export const ToolKind = z
  .enum([
    'bash',
    'fileRead',
    'fileWrite',
    'fileEdit',
    'notebookEdit',
    'grep',
    'glob',
    'webFetch',
    'webSearch',
    'mcp',
    'subagent',
    'todoWrite',
    'task',
    'askUserQuestion',
    'exitPlanMode',
    'enterPlanMode',
    'skill',
    'monitor',
    'schedule',
    'worktree',
    'other',
  ])
  .meta({ id: 'ToolKind' });
export type ToolKind = z.infer<typeof ToolKind>;

export const ToolStatus = z
  .enum(['pending', 'running', 'completed', 'failed', 'denied', 'interrupted'])
  .meta({ id: 'ToolStatus' });
export type ToolStatus = z.infer<typeof ToolStatus>;

const base = {
  id: z.string(),
  turnId: z.string().nullable(),
  /** Set when the item was produced inside a subagent (the parent Task/Agent tool_use id). */
  parentToolUseId: z.string().nullable(),
  createdAt: z.number().describe('ms since epoch'),
};

export const UserMessageItem = z.object({
  type: z.literal('userMessage'),
  ...base,
  content: z.array(UserInput),
  /** Sent while a turn was running; delivered into that turn. */
  queued: z.boolean().optional(),
  /** Generated by Claude Code (skill expansion, compaction summary, hook context), not typed by the user. */
  synthetic: z.boolean().optional(),
  /** Provenance for non-human messages, e.g. task-notification, peer, channel. */
  origin: z.string().optional(),
});

export const AgentMessageItem = z.object({
  type: z.literal('agentMessage'),
  ...base,
  text: z.string(),
  model: z.string().optional(),
});

export const ReasoningItem = z.object({
  type: z.literal('reasoning'),
  ...base,
  text: z.string(),
  /** Thinking happened but its text was not returned (display omitted or redacted). */
  redacted: z.boolean().optional(),
});

export const ToolCallItem = z.object({
  type: z.literal('toolCall'),
  ...base,
  name: z.string(),
  kind: ToolKind,
  input: JsonValue,
  status: ToolStatus,
  /** Text content of the tool_result sent to the model. */
  outputText: z.string().optional(),
  /** Tool's structured Output object (see sdk-tools *Output types), when available. */
  output: JsonValue.optional(),
  isError: z.boolean().optional(),
  mcpServer: z.string().optional(),
  elapsedSeconds: z.number().optional(),
  summary: z.string().optional(),
});

export const CompactionItem = z.object({
  type: z.literal('compaction'),
  ...base,
  trigger: z.enum(['manual', 'auto']).optional(),
  preTokens: z.number().optional(),
  postTokens: z.number().optional(),
});

export const ErrorItem = z.object({
  type: z.literal('error'),
  ...base,
  message: z.string(),
  code: z.string().optional(),
});

export const NoticeItem = z.object({
  type: z.literal('notice'),
  ...base,
  kind: z.string().describe('localCommandOutput | informational | hook | modelFallback | …'),
  text: z.string(),
  level: z.enum(['info', 'warning', 'error']).optional(),
});

export const Item = z
  .discriminatedUnion('type', [
    UserMessageItem,
    AgentMessageItem,
    ReasoningItem,
    ToolCallItem,
    CompactionItem,
    ErrorItem,
    NoticeItem,
  ])
  .meta({ id: 'Item' });
export type Item = z.infer<typeof Item>;
export type ToolCallItem = z.infer<typeof ToolCallItem>;

export const TurnStatus = z.enum(['inProgress', 'completed', 'interrupted', 'failed']).meta({ id: 'TurnStatus' });

export const TurnResult = z
  .object({
    subtype: z.string().describe('success | error_max_turns | error_during_execution | error_max_budget_usd | …'),
    isError: z.boolean(),
    resultText: z.string().optional(),
    stopReason: z.string().nullable().optional(),
    terminalReason: z.string().optional(),
    errors: z.array(z.string()).optional(),
    durationMs: z.number(),
    durationApiMs: z.number(),
    numTurns: z.number(),
    totalCostUsd: z.number(),
    usage: Usage,
    modelUsage: z.record(z.string(), ModelUsage),
  })
  .meta({ id: 'TurnResult' });
export type TurnResult = z.infer<typeof TurnResult>;

export const Turn = z
  .object({
    id: z.string(),
    status: TurnStatus,
    startedAt: z.number(),
    completedAt: z.number().optional(),
    result: TurnResult.optional(),
  })
  .meta({ id: 'Turn' });
export type Turn = z.infer<typeof Turn>;
