import { z } from 'zod';
import { JsonValue, ModelUsage, Usage, UserInput } from './common.ts';

export const ToolKind = z
  .enum([
    'bash',
    'fileRead',
    'fileWrite',
    'fileEdit',
    'notebookEdit',
    'grep',
    'glob',
    'webFetch',
    'webSearch',
    'mcp',
    'subagent',
    'todoWrite',
    'task',
    'askUserQuestion',
    'exitPlanMode',
    'enterPlanMode',
    'skill',
    'monitor',
    'schedule',
    'worktree',
    'other',
  ])
  .meta({ id: 'ToolKind' });
export type ToolKind = z.infer<typeof ToolKind>;

export const ToolStatus = z
  .enum(['pending', 'running', 'completed', 'failed', 'denied', 'interrupted'])
  .meta({ id: 'ToolStatus' });
export type ToolStatus = z.infer<typeof ToolStatus>;

const base = {
  id: z.string(),
  turnId: z.string().nullable(),
  /** Set when the item was produced inside a subagent (the parent Task/Agent tool_use id). */
  parentToolUseId: z.string().nullable(),
  createdAt: z.number().describe('ms since epoch'),
};

export const UserMessageItem = z.object({
  type: z.literal('userMessage'),
  ...base,
  content: z.array(UserInput),
  /** Sent while a turn was running; delivered into that turn. */
  queued: z.boolean().optional(),
  /** Generated by Claude Code (skill expansion, compaction summary, hook context), not typed by the user. */
  synthetic: z.boolean().optional(),
  /**
   * Provenance for non-human messages, e.g. task-notification, peer, channel, subagent, or
   * `workflow`: a dynamic workflow's finish, `workflow_<taskId>_finished`, whose content is its
   * result (or, failed or stopped, what happened) and whose `originName` is the workflow's name. It
   * may first come with the CLI's summary and then again, the same id, with the result; or
   * `wakeup`: a scheduled job firing (a /loop, CronCreate or ScheduleWakeup), whose content is
   * the prompt it fired with. It opens the turn it starts, live and in history: id and turn id are
   * the CLI's command uuid. The CLI never echoes it as a message, so it is read from the transcript.
   */
  origin: z.string().optional(),
  /** For a message from another session: the sender's display name, as it reported it. */
  originName: z.string().optional(),
  /** For a message from another session: the sending session's id, to link back to it. */
  originSession: z.string().optional(),
});

export const AgentMessageItem = z.object({
  type: z.literal('agentMessage'),
  ...base,
  text: z.string(),
  model: z.string().optional(),
});

export const ReasoningItem = z.object({
  type: z.literal('reasoning'),
  ...base,
  text: z.string(),
  /** Thinking happened but its text was not returned (display omitted or redacted). */
  redacted: z.boolean().optional(),
});

export const ToolCallItem = z.object({
  type: z.literal('toolCall'),
  ...base,
  name: z.string(),
  kind: ToolKind,
  input: JsonValue,
  status: ToolStatus,
  /** Text content of the tool_result sent to the model. */
  outputText: z.string().optional(),
  /** Tool's structured Output object (see sdk-tools *Output types), when available. */
  output: JsonValue.optional(),
  isError: z.boolean().optional(),
  mcpServer: z.string().optional(),
  elapsedSeconds: z.number().optional(),
  summary: z.string().optional(),
});

export const CompactionItem = z.object({
  type: z.literal('compaction'),
  ...base,
  trigger: z.enum(['manual', 'auto']).optional(),
  preTokens: z.number().optional(),
  postTokens: z.number().optional(),
});

export const ErrorItem = z.object({
  type: z.literal('error'),
  ...base,
  message: z.string(),
  code: z.string().optional(),
});

/** What happened to a /goal: set, a check that found it not met yet, met, failed (impossible), or cleared. */
export const GoalEvent = z.enum(['set', 'notMet', 'met', 'failed', 'cleared']).meta({ id: 'GoalEvent' });
export type GoalEvent = z.infer<typeof GoalEvent>;

/** A /goal's condition and what its Stop hook last said of it, on a `goal` notice. */
export const GoalNotice = z
  .object({
    condition: z.string(),
    event: GoalEvent,
    /** Why a check found it met, not met yet, or impossible: the evaluator's words. */
    reason: z.string().optional(),
    /** How many checks it took, when the CLI says (on met and failed). */
    iterations: z.number().optional(),
    durationMs: z.number().optional(),
  })
  .meta({ id: 'GoalNotice' });
export type GoalNotice = z.infer<typeof GoalNotice>;

export const NoticeItem = z.object({
  type: z.literal('notice'),
  ...base,
  kind: z.string().describe('localCommandOutput | informational | hook | modelFallback | goal | …'),
  text: z.string(),
  level: z.enum(['info', 'warning', 'error']).optional(),
  /**
   * Kind `goal`: a /goal set or cleared (the command's own output), or what a check of it found
   * (the CLI's `goal_status`, written to the transcript only, so read from there live too).
   */
  goal: GoalNotice.optional(),
});

export const WorkflowPhase = z
  .object({ index: z.number(), title: z.string(), detail: z.string().optional() })
  .meta({ id: 'WorkflowPhase' });

export const WorkflowAgent = z
  .object({
    index: z.number(),
    label: z.string(),
    phaseIndex: z.number().optional(),
    phaseTitle: z.string().optional(),
    agentId: z.string().optional(),
    model: z.string().optional(),
    /**
     * The CLI's own state, passed through as it came: start (queued or starting), progress, done,
     * error, and whatever a later CLI adds. A skipped agent is `error` with `skipped`.
     */
    state: z.string(),
    /**
     * Skipped by the person (the CLI reports it as state `error`, "skipped by user"), or never
     * started: still waiting for a slot when its workflow completed.
     */
    skipped: z.boolean().optional(),
    /** Replayed from an earlier run's cache rather than run again. */
    cached: z.boolean().optional(),
    /** Stopped by the safety classifier before it ran. */
    blocked: z.boolean().optional(),
    queuedAt: z.number().optional(),
    startedAt: z.number().optional(),
    durationMs: z.number().optional(),
    tokens: z.number().optional(),
    toolCalls: z.number().optional(),
    lastToolName: z.string().optional(),
    lastToolSummary: z.string().optional(),
    promptPreview: z.string().optional(),
    resultPreview: z.string().optional(),
    error: z.string().optional(),
  })
  .meta({ id: 'WorkflowAgent' });

/** A dynamic workflow (the Workflow tool's `local_workflow` task): its phases and agents, as the CLI reports them. */
export const WorkflowSnapshot = z
  .object({
    runId: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    /**
     * running | completed | failed | stopped | paused, or unknown: a run found only by its journal,
     * with no live task and no record, nothing of it written for a few minutes, which may have been
     * cut off. A journal-only run written to recently is reported running.
     */
    status: z.string().optional(),
    /** the latest agent event, "Phase: label" */
    activity: z.string().optional(),
    phases: z.array(WorkflowPhase),
    agents: z.array(WorkflowAgent),
    totalTokens: z.number().optional(),
    toolUses: z.number().optional(),
    durationMs: z.number().optional(),
    /** the workflow's return value as text, once it has completed */
    result: z.string().optional(),
    /** why it failed */
    error: z.string().optional(),
  })
  .meta({ id: 'WorkflowSnapshot' });
export type WorkflowSnapshot = z.infer<typeof WorkflowSnapshot>;
export type WorkflowAgent = z.infer<typeof WorkflowAgent>;
export type WorkflowPhase = z.infer<typeof WorkflowPhase>;

export const Item = z
  .discriminatedUnion('type', [
    UserMessageItem,
    AgentMessageItem,
    ReasoningItem,
    ToolCallItem,
    CompactionItem,
    ErrorItem,
    NoticeItem,
  ])
  .meta({ id: 'Item' });
export type Item = z.infer<typeof Item>;
export type ToolCallItem = z.infer<typeof ToolCallItem>;

export const TurnStatus = z.enum(['inProgress', 'completed', 'interrupted', 'failed']).meta({ id: 'TurnStatus' });

export const TurnResult = z
  .object({
    subtype: z.string().describe('success | error_max_turns | error_during_execution | error_max_budget_usd | …'),
    isError: z.boolean(),
    resultText: z.string().optional(),
    stopReason: z.string().nullable().optional(),
    terminalReason: z.string().optional(),
    errors: z.array(z.string()).optional(),
    durationMs: z.number(),
    durationApiMs: z.number(),
    numTurns: z.number(),
    totalCostUsd: z.number(),
    usage: Usage,
    modelUsage: z.record(z.string(), ModelUsage),
  })
  .meta({ id: 'TurnResult' });
export type TurnResult = z.infer<typeof TurnResult>;

export const Turn = z
  .object({
    id: z.string(),
    status: TurnStatus,
    startedAt: z.number(),
    completedAt: z.number().optional(),
    result: TurnResult.optional(),
  })
  .meta({ id: 'Turn' });
export type Turn = z.infer<typeof Turn>;
